name: flutter_graphql
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 1.0.0-rc.1
authors:
  - Rex Raphael <rex.raphael@outlook.com>
homepage: https://github.com/juicycleff/graphql-flutter/tree/master

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  http: ^0.12.0
  http_parser: ^3.1.3
  path_provider: ^0.4.1
  uuid: ^1.0.3
  sqflite: ^1.1.0
  graphql_parser: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0

environment:
  sdk: ">=2.0.0 <3.0.0"
